// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/**
 * A Context carries a deadline, a cancellation signal, and other values across
 * API boundaries.
 * 
 * Context's methods may be called by multiple goroutines simultaneously.
 */
export type Context = any;
