// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../discord/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export type Client = any;

export interface Instance {
    "User": types$0.User | null;
    "Client": Client;
    "GuildID": string;
    "Cfg": config$0.Config;
    "AccountCfg": config$0.AccountsConfig;
    "LastRan": { [_: string]: time$0.Time } | null;
    "StopChan": any;
    "State": string;
    "Ctx": context$0.Context;
    "IsRestarting": boolean;
    "AutoBuyResultChan": any;
    "BreakUpdateTime": time$0.Time;
}

export interface View {
    "user": types$0.User | null;
    "accountCfg": config$0.AccountsConfig;
    "state"?: string;
    "breakUpdateTime"?: string;
}
