// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as config$0 from "../../../../autocord-org/dmg/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as instance$0 from "../../../../autocord-org/dmg/instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as utils$0 from "../../../../autocord-org/dmg/utils/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "configUpdate": config$0.Config;
            "instanceUpdate": instance$0.View;
            "log": utils$0.LogEvent;
        }
    }
}
