// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LogEvent {
    "level": LogLevel;
    "type": LogType;
    "username": string;
    "message": string;
}

export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Important = "important",
    Others = "others",
    Discord = "discord",
};

export enum LogType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Info = "INF",
    Error = "ERR",
};
