// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../discord/types/models.js";

export interface AccountsConfig {
    "token": string;
    "channelID": string;
    "state": boolean;
}

export interface AdventureCommandConfig {
    "state": boolean;
    "delay": number;
    "adventureOption": AdventureOption;
}

export interface AdventureConfig {
    "space": { [_: string]: string } | null;
    "west": { [_: string]: string } | null;
    "brazil": { [_: string]: string } | null;
    "vacation": { [_: string]: string } | null;
}

export enum AdventureOption {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Brazil = "brazil",
    Space = "space",
    Vacation = "vacation",
    West = "west",
};

export interface AutoBuyConfig {
    "huntingRifle": GeneralAutobuyConfig;
    "shovel": GeneralAutobuyConfig;
    "lifeSavers": GeneralAutobuyConfig;
}

export interface AutoUseConfig {
    "apple": GeneralAutoUseConfig;
    "luckyHorseshoe": GeneralAutoUseConfig;
    "pizzaSlice": GeneralAutoUseConfig;
}

export interface BlackjackCommandConfig {
    "state": boolean;
    "delay": number;
    "amount": string;
    "manuallyRunCommands": boolean;
}

export interface CommandsConfig {
    "adventure": AdventureCommandConfig;
    "beg": GeneralCommandConfig;
    "blackjack": BlackjackCommandConfig;
    "crime": CrimeCommandConfig;
    "daily": GeneralCommandConfig;
    "deposit": GeneralCommandConfig;
    "dig": GeneralCommandConfig;
    "fish": FishCommandConfig;
    "highlow": GeneralCommandConfig;
    "hunt": GeneralCommandConfig;
    "pets": GeneralCommandConfig;
    "postmemes": PostMemesCommandConfig;
    "scratch": GeneralCommandConfig;
    "search": SearchCommandConfig;
    "stream": StreamCommandConfig;
    "trivia": TriviaCommandConfig;
    "work": WorkCommandConfig;
}

export interface Config {
    "state": boolean;
    "apiKey": string;
    "gui": GuiConfig;
    "readAlerts": boolean;
    "discordStatus": types$0.OnlineStatus;
    "eventsCorrectChance": number;
    "cooldowns": Cooldowns;
    "accounts": AccountsConfig[] | null;
    "autoBuy": AutoBuyConfig;
    "autoUse": AutoUseConfig;
    "commands": CommandsConfig;
    "adventure": AdventureConfig;
}

export interface Cooldowns {
    "buttonClickDelay": DelaySeconds;
    "commandInterval": DelaySeconds;
    "breakCooldown": DelayHours;
    "breakDuration": DelayHours;
    "startDelay": DelayMinutes;
    "eventDelay": DelaySeconds;
}

export interface CrimeCommandConfig {
    "state": boolean;
    "delay": number;
    "priority": string[] | null;
    "secondPriority": string[] | null;
    "avoid": string[] | null;
}

export interface DelayHours {
    "minHours": number;
    "maxHours": number;
}

export interface DelayMinutes {
    "minMinutes": number;
    "maxMinutes": number;
}

export interface DelaySeconds {
    "minSeconds": number;
    "maxSeconds": number;
}

export interface FishCommandConfig {
    "state": boolean;
    "delay": number;
    "fishOnly": boolean;
    "fishOnlyDelay": DelaySeconds;
    "autoCompleteTasks": boolean;
    "autoCompleteTradeOffers": boolean;
    "autoEquipment": boolean;
    "sellCoinsValue": number;
    "fishLocation": FishLocation[] | null;
}

export enum FishLocation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VertigoBeach = "Vertigo Beach",
    WilyRiver = "Wily River",
    UnderwaterSanctuary = "Underwater Sanctuary",
    CampGuillermo = "Camp Guillermo",
    ScurvyWaters = "Scurvy Waters",
    NorthpointCabin = "Northpoint Cabin",
};

export interface GeneralAutoUseConfig {
    "state": boolean;
}

export interface GeneralAutobuyConfig {
    "state": boolean;
    "amount": number;
}

export interface GeneralCommandConfig {
    "state": boolean;
    "delay": number;
}

export interface GuiConfig {
    "theme": Theme;
}

export interface PostMemesCommandConfig {
    "state": boolean;
    "delay": number;
    "platform": number[] | null;
}

export interface SearchCommandConfig {
    "state": boolean;
    "delay": number;
    "priority": string[] | null;
    "secondPriority": string[] | null;
    "avoid": string[] | null;
}

export interface StreamCommandConfig {
    "state": boolean;
    "delay": number;
    "order": number[] | null;
}

export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    System = "system",
    Dark = "dark",
    Light = "light",
};

export interface TriviaCommandConfig {
    "state": boolean;
    "delay": number;
    "triviaCorrectChance": number;
}

export interface WorkCommandConfig {
    "state": boolean;
    "delay": number;
    "autoWorkApply": boolean;
}
