// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/**
 * OnlineStatus (https://discord.com/developers/docs/topics/gateway#update-presence-status-types)
 */
export enum OnlineStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OnlineStatusOnline = "online",
    OnlineStatusDND = "dnd",
    OnlineStatusIdle = "idle",
    OnlineStatusInvisible = "invisible",
    OnlineStatusOffline = "offline",
};

export interface User {
    "id": string;
    "username": string;
    "discriminator": string;
    "avatar": string;
    "bot"?: boolean;
    "system"?: boolean;
    "mfa_enabled"?: boolean;
    "locale"?: string;
    "verified"?: boolean;
    "email"?: string;
    "status"?: OnlineStatus;
}
