// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./discord/types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfig(): Promise<config$0.Config | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2704585121) as any;
    return $resultPromise;
}

export function GetInstances(): Promise<($models.InstanceView | null)[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1143882985) as any;
    return $resultPromise;
}

export function RemoveInstance(token: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(286226590, token) as any;
    return $resultPromise;
}

export function RestartInstance(token: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1855792867, token) as any;
    return $resultPromise;
}

export function RestartInstances(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2976101552) as any;
    return $resultPromise;
}

export function StartInstance(account: config$0.AccountsConfig): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1056784576, account) as any;
    return $resultPromise;
}

export function StartInstances(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3685538249) as any;
    return $resultPromise;
}

export function UpdateConfig(newCfg: config$0.Config | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2546091902, newCfg) as any;
    return $resultPromise;
}

export function UpdateDiscordStatus(status: types$0.OnlineStatus): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3790660754, status) as any;
    return $resultPromise;
}

export function UpdateInstanceToken(oldToken: string, newToken: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(125248392, oldToken, newToken) as any;
    return $resultPromise;
}
