// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./discord/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export function CheckForUpdates(): $CancellablePromise<boolean> {
    return $Call.ByID(1803947812);
}

export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2704585121);
}

export function GetIndex(token: string): $CancellablePromise<number> {
    return $Call.ByID(1338406745, token);
}

export function RemoveInstance(token: string, restarting: boolean): $CancellablePromise<void> {
    return $Call.ByID(286226590, token, restarting);
}

export function RestartInstance(token: string): $CancellablePromise<instance$0.View | null> {
    return $Call.ByID(1855792867, token);
}

export function RestartInstances(): $CancellablePromise<void> {
    return $Call.ByID(2976101552);
}

export function StartInstance(account: config$0.AccountsConfig, readyState: string, breakUpdateTime: time$0.Time): $CancellablePromise<void> {
    return $Call.ByID(1056784576, account, readyState, breakUpdateTime);
}

export function StartInstances(): $CancellablePromise<void> {
    return $Call.ByID(3685538249);
}

export function Update(): $CancellablePromise<void> {
    return $Call.ByID(749024496);
}

export function UpdateConfig(newCfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(2546091902, newCfg);
}

export function UpdateDiscordStatus(status: types$0.OnlineStatus): $CancellablePromise<void> {
    return $Call.ByID(3790660754, status);
}

export function UpdateInstance(ins: instance$0.Instance | null): $CancellablePromise<void> {
    return $Call.ByID(2920987275, ins);
}

export function UpdateInstanceToken(oldToken: string, newToken: string): $CancellablePromise<void> {
    return $Call.ByID(125248392, oldToken, newToken);
}
