// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DmgService from "./dmgservice.js";
export {
    DmgService
};

export * from "./models.js";
