// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./discord/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface InstanceView {
    "user": types$0.User | null;
    "channelID": string;
    "guildID": string;
    "config": config$0.Config;
    "accountCfg": config$0.AccountsConfig;
    "lastRan": { [_: string]: time$0.Time } | null;
    "pause": boolean;
    "error"?: string;
}
