// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetInstances():Promise<Array<main.InstanceView>>;

export function RemoveInstance(arg1:string):Promise<void>;

export function RestartInstance(arg1:string):Promise<void>;

export function RestartInstances():Promise<void>;

export function StartInstance(arg1:config.AccountsConfig):Promise<void>;

export function StartInstances():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateDiscordStatus(arg1:string):Promise<void>;

export function UpdateInstanceToken(arg1:string,arg2:string):Promise<void>;
