// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function RemoveInstance(arg1) {
  return window['go']['main']['App']['RemoveInstance'](arg1);
}

export function RestartInstance(arg1) {
  return window['go']['main']['App']['RestartInstance'](arg1);
}

export function RestartInstances() {
  return window['go']['main']['App']['RestartInstances']();
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstances() {
  return window['go']['main']['App']['StartInstances']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateDiscordStatus(arg1) {
  return window['go']['main']['App']['UpdateDiscordStatus'](arg1);
}

export function UpdateInstanceToken(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceToken'](arg1, arg2);
}
