// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return ObfuscatedCall(0, []);
}

export function GetInstances() {
  return ObfuscatedCall(1, []);
}

export function RemoveInstance(arg1) {
  return ObfuscatedCall(2, [arg1]);
}

export function RestartInstance(arg1) {
  return ObfuscatedCall(3, [arg1]);
}

export function RestartInstances() {
  return ObfuscatedCall(4, []);
}

export function StartInstance(arg1) {
  return ObfuscatedCall(5, [arg1]);
}

export function StartInstances() {
  return ObfuscatedCall(6, []);
}

export function UpdateConfig(arg1) {
  return ObfuscatedCall(7, [arg1]);
}

export function UpdateDiscordStatus(arg1) {
  return ObfuscatedCall(8, [arg1]);
}

export function UpdateInstanceToken(arg1, arg2) {
  return ObfuscatedCall(9, [arg1, arg2]);
}
